services:
  postgres:
    image: postgres:18-alpine
    container_name: hospital_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_password
    ports:
      - '5432:5432'
    volumes:
      - hospital_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hospital_user -d hospital_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: redgate/flyway
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/hospital_db
      FLYWAY_USER: hospital_user
      FLYWAY_PASSWORD: hospital_password
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
      FLYWAY_DEFAULT_MIGRATION_NAMING: "true"
    volumes:
      - ./migrations:/flyway/sql:ro
    depends_on:
      - postgres

volumes:
  hospital_postgres_data: