INSERT INTO clinical.doctors (staff_member_id,
                              medical_license_number,
                              specialization,
                              is_available_for_appointments)
VALUES ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000001'),
        'HPCSA-MP-100001', 'General Medicine', TRUE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000002'),
        'HPCSA-MP-100002', 'Cardiology', TRUE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000003'),
        'HPCSA-MP-100003', 'Orthopedic Surgery', TRUE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000005'),
        'HPCSA-MP-100005', 'General Surgery', TRUE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000006'),
        'HPCSA-MP-100006', 'Pediatrics', TRUE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000007'),
        'HPCSA-MP-100007', 'Neurosurgery', FALSE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000009'),
        'HPCSA-MP-100009', 'Cardiothoracic Surgery', TRUE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000010'),
        'HPCSA-MP-100010', 'Radiology', TRUE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000011'),
        'HPCSA-MP-100011', 'Oncology', TRUE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000012'),
        'HPCSA-MP-100012', 'General Surgery', TRUE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000013'),
        'HPCSA-MP-100013', 'Otolaryngology', TRUE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000015'),
        'HPCSA-MP-100015', 'Pediatric Surgery', TRUE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000018'),
        'HPCSA-MP-100018', 'Urology', TRUE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000019'),
        'HPCSA-MP-100019', 'Gastroenterology', FALSE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000021'),
        'HPCSA-MP-100021', 'Trauma Surgery', TRUE),
       ((SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000022'),
        'HPCSA-MP-100022', 'General Surgery', TRUE);

INSERT INTO clinical.appointments (appointment_number,
                                   patient_id,
                                   doctor_id,
                                   created_by_staff_id,
                                   appointment_start,
                                   appointment_end,
                                   appointment_type,
                                   status,
                                   reason,
                                   notes)
VALUES

('APT-2026-000001',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000001'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000001'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000023'),
    CURRENT_DATE + INTERVAL '1 days' + INTERVAL '8 hours',
    CURRENT_DATE + INTERVAL '1 days' + INTERVAL '8 hours 30 minutes',
    'CONSULTATION', 'SCHEDULED', 'Routine check-up', NULL),

('APT-2026-000002',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000002'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000002'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000023'),
 CURRENT_DATE + INTERVAL '1 days' + INTERVAL '9 hours',
 CURRENT_DATE + INTERVAL '1 days' + INTERVAL '9 hours 15 minutes',
    'FOLLOW_UP', 'CONFIRMED', 'Post-op cardiac follow-up', 'Patient reports mild chest discomfort'),

('APT-2026-000003',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000003'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000003'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000023'),
 CURRENT_DATE + INTERVAL '1 days' + INTERVAL '10 hours',
 CURRENT_DATE + INTERVAL '1 days' + INTERVAL '10 hours 30 minutes',
    'CONSULTATION', 'SCHEDULED', 'Knee pain after fall', NULL),

('APT-2026-000004',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000005'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000006'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000023'),
 CURRENT_DATE + INTERVAL '1 days' + INTERVAL '11 hours',
 CURRENT_DATE + INTERVAL '1 days' + INTERVAL '11 hours 20 minutes',
    'CONSULTATION', 'SCHEDULED', 'Childhood vaccination review', NULL),

('APT-2026-000005',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000007'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000001'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000023'),
 CURRENT_DATE + INTERVAL '1 days' + INTERVAL '8 hours 30 minutes',
 CURRENT_DATE + INTERVAL '1 days' + INTERVAL '9 hours',
    'CONSULTATION', 'SCHEDULED', 'Persistent headaches', NULL),

('APT-2026-000006',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000008'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000009'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000023'),
 CURRENT_DATE + INTERVAL '2 days' + INTERVAL '13 hours',
 CURRENT_DATE + INTERVAL '2 days' + INTERVAL '14 hours',
    'SPECIALIST_REFERRAL', 'CONFIRMED', 'Suspected arrhythmia', 'Referred from general practice'),

('APT-2026-000007',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000010'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000010'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000023'),
 CURRENT_DATE + INTERVAL '2 days' + INTERVAL '9 hours',
 CURRENT_DATE + INTERVAL '2 days' + INTERVAL '9 hours 30 minutes',
    'LAB_REVIEW', 'SCHEDULED', 'MRI results review', NULL),

('APT-2026-000008',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000004'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000011'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000024'),
 CURRENT_DATE - INTERVAL '2 days' + INTERVAL '10 hours',
 CURRENT_DATE - INTERVAL '2 days' + INTERVAL '11 hours',
    'CONSULTATION', 'COMPLETED', 'Oncology follow-up', 'Continue current treatment plan'),

('APT-2026-000009',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000009'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000012'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000023'),
 CURRENT_DATE + INTERVAL '3 days' + INTERVAL '8 hours',
 CURRENT_DATE + INTERVAL '3 days' + INTERVAL '8 hours 45 minutes',
    'CONSULTATION', 'SCHEDULED', 'Abdominal pain investigation', NULL),

('APT-2026-000010',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000011'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000013'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000023'),
 CURRENT_DATE + INTERVAL '3 days' + INTERVAL '14 hours',
 CURRENT_DATE + INTERVAL '3 days' + INTERVAL '14 hours 30 minutes',
    'CONSULTATION', 'SCHEDULED', 'Chronic sinus congestion', NULL),

('APT-2026-000011',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000012'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000015'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000024'),
 CURRENT_DATE + INTERVAL '4 days' + INTERVAL '9 hours',
 CURRENT_DATE + INTERVAL '4 days' + INTERVAL '9 hours 30 minutes',
    'CONSULTATION', 'SCHEDULED', 'Growth and development check', NULL),

('APT-2026-000012',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000013'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000018'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000023'),
 CURRENT_DATE + INTERVAL '4 days' + INTERVAL '11 hours',
 CURRENT_DATE + INTERVAL '4 days' + INTERVAL '11 hours 30 minutes',
    'FOLLOW_UP', 'CANCELLED', 'Post-surgical review', 'Patient cancelled due to transport issues'),

('APT-2026-000013',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000015'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000021'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000023'),
 CURRENT_DATE + INTERVAL '7 hours 30 minutes',
 CURRENT_DATE + INTERVAL '8 hours 15 minutes',
    'EMERGENCY', 'IN_PROGRESS', 'Motor vehicle accident, multiple trauma', 'Trauma team activated'),

('APT-2026-000014',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000003'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000022'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000024'),
 CURRENT_DATE + INTERVAL '5 days' + INTERVAL '8 hours',
 CURRENT_DATE + INTERVAL '5 days' + INTERVAL '8 hours 30 minutes',
    'CONSULTATION', 'NO_SHOW', 'Pre-surgical assessment', 'Patient did not arrive'),

('APT-2026-000015',
    (SELECT id FROM clinical.patients WHERE patient_number = 'PAT-2026-000001'),
    (SELECT d.id FROM clinical.doctors d JOIN clinical.staff_members s ON s.id = d.staff_member_id WHERE s.staff_number = 'STF-2026-000001'),
    (SELECT id FROM clinical.staff_members WHERE staff_number = 'STF-2026-000023'),
 CURRENT_DATE + INTERVAL '8 days' + INTERVAL '8 hours',
 CURRENT_DATE + INTERVAL '8 days' + INTERVAL '8 hours 30 minutes',
    'FOLLOW_UP', 'SCHEDULED', 'Blood pressure recheck', NULL);