INSERT INTO clinical.departments (department_code,
                                  name,
                                  description)
VALUES ('EMR', 'Emergency', 'Handles emergency and trauma cases'),
       ('GEN', 'General Medicine', 'Handles general consultations and primary care'),
       ('CARD', 'Cardiology', 'Handles heart-related conditions'),
       ('ORTH', 'Orthopedics', 'Handles bone, joint, and muscle conditions'),
       ('PED', 'Pediatrics', 'Handles care for infants, children, and adolescents'),
       ('NEUR', 'Neurology', 'Handles disorders of the brain and nervous system'),
       ('OBGY', 'Obstetrics & Gynecology', 'Handles pregnancy, childbirth, and women''s health'),
       ('DERM', 'Dermatology', 'Handles skin, hair, and nail conditions'),
       ('RAD', 'Radiology', 'Handles imaging and diagnostic scans'),
       ('ONC', 'Oncology', 'Handles cancer diagnosis and treatment'),
       ('PSYC', 'Psychiatry', 'Handles mental health and behavioral conditions'),
       ('ENT', 'Otolaryngology', 'Handles ear, nose, and throat conditions'),
       ('URO', 'Urology', 'Handles urinary tract and male reproductive conditions'),
       ('GAST', 'Gastroenterology', 'Handles digestive system conditions'),
       ('PULM', 'Pulmonology', 'Handles lung and respiratory conditions'),
       ('ANES', 'Anesthesiology', 'Handles anesthesia and perioperative care'),
       ('LAB', 'Pathology / Lab', 'Handles laboratory testing and diagnostics'),
       ('PHAR', 'Pharmacy', 'Handles medication dispensing and management'),
       ('ICU', 'Intensive Care Unit', 'Handles critically ill patients requiring intensive monitoring'),
       ('ADMN', 'Administration', 'Handles hospital administration and billing');

INSERT INTO clinical.staff_members (staff_number,
                                    first_name,
                                    last_name,
                                    role,
                                    department_id,
                                    phone_number,
                                    email,
                                    employment_status,
                                    hired_at)
VALUES ('STF-2026-000001',
        'John',
        'Nkosi',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'GEN'),
        '+27830000001',
        'john.nkosi@hospital.test',
        'ACTIVE',
        '2018-03-14'),
       ('STF-2026-000002',
        'Thandiwe',
        'Dlamini',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'CARD'),
        '+27830000002',
        'thandiwe.dlamini@hospital.test',
        'ACTIVE',
        '2015-07-01'),
       ('STF-2026-000003',
        'Pieter',
        'van der Merwe',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'ORTH'),
        '+27830000003',
        'pieter.vandermerwe@hospital.test',
        'ACTIVE',
        '2020-01-20'),
       ('STF-2026-000004',
        'Nomvula',
        'Khumalo',
        'NURSE',
        (SELECT id FROM clinical.departments WHERE department_code = 'EMR'),
        '+27830000004',
        'nomvula.khumalo@hospital.test',
        'ACTIVE',
        '2019-05-11'),
       ('STF-2026-000005',
        'Meredith',
        'Grey',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'GEN'),
        '+27830000005',
        'meredith.grey@hospital.test',
        'ACTIVE',
        '2016-09-01'),
       ('STF-2026-000006',
        'Aisha',
        'Patel',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'PED'),
        '+27830000006',
        'aisha.patel@hospital.test',
        'ACTIVE',
        '2021-02-08'),
       ('STF-2026-000007',
        'Derek',
        'Shepherd',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'NEUR'),
        '+27830000007',
        'derek.shepherd@hospital.test',
        'ACTIVE',
        '2014-11-19'),
       ('STF-2026-000008',
        'Lindiwe',
        'Zulu',
        'NURSE',
        (SELECT id FROM clinical.departments WHERE department_code = 'OBGY'),
        '+27830000008',
        'lindiwe.zulu@hospital.test',
        'ON_LEAVE',
        '2017-06-23'),
       ('STF-2026-000009',
        'Cristina',
        'Yang',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'CARD'),
        '+27830000009',
        'cristina.yang@hospital.test',
        'ACTIVE',
        '2013-08-30'),
       ('STF-2026-000010',
        'Zanele',
        'Ndlovu',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'RAD'),
        '+27830000010',
        'zanele.ndlovu@hospital.test',
        'ACTIVE',
        '2019-10-02'),
       ('STF-2026-000011',
        'David',
        'Cohen',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'ONC'),
        '+27830000011',
        'david.cohen@hospital.test',
        'ACTIVE',
        '2012-04-16'),
       ('STF-2026-000012',
        'Miranda',
        'Bailey',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'GEN'),
        '+27830000012',
        'miranda.bailey@hospital.test',
        'ACTIVE',
        '2009-01-05'),
       ('STF-2026-000013',
        'Willem',
        'du Toit',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'ENT'),
        '+27830000013',
        'willem.dutoit@hospital.test',
        'ACTIVE',
        '2022-03-11'),
       ('STF-2026-000014',
        'Nokuthula',
        'Mahlangu',
        'NURSE',
        (SELECT id FROM clinical.departments WHERE department_code = 'ICU'),
        '+27830000014',
        'nokuthula.mahlangu@hospital.test',
        'ACTIVE',
        '2018-12-01'),
       ('STF-2026-000015',
        'Alex',
        'Karev',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'PED'),
        '+27830000015',
        'alex.karev@hospital.test',
        'ACTIVE',
        '2015-05-22'),
       ('STF-2026-000016',
        'Fatima',
        'Ismail',
        'PHARMACIST',
        (SELECT id FROM clinical.departments WHERE department_code = 'PHAR'),
        '+27830000016',
        'fatima.ismail@hospital.test',
        'ACTIVE',
        '2020-07-14'),
       ('STF-2026-000017',
        'Tebogo',
        'Molefe',
        'LAB_TECHNICIAN',
        (SELECT id FROM clinical.departments WHERE department_code = 'LAB'),
        '+27830000017',
        'tebogo.molefe@hospital.test',
        'ACTIVE',
        '2021-09-06'),
       ('STF-2026-000018',
        'Michael',
        'Naidoo',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'URO'),
        '+27830000018',
        'michael.naidoo@hospital.test',
        'ACTIVE',
        '2011-02-28'),
       ('STF-2026-000019',
        'Izzie',
        'Stevens',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'GAST'),
        '+27830000019',
        'izzie.stevens@hospital.test',
        'TERMINATED',
        '2010-06-01'),
       ('STF-2026-000020',
        'Andries',
        'Fourie',
        'NURSE',
        (SELECT id FROM clinical.departments WHERE department_code = 'PULM'),
        '+27830000020',
        'andries.fourie@hospital.test',
        'ACTIVE',
        '2019-04-09'),
       ('STF-2026-000021',
        'Owen',
        'Hunt',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'EMR'),
        '+27830000021',
        'owen.hunt@hospital.test',
        'ACTIVE',
        '2014-03-17'),
       ('STF-2026-000022',
        'Richard',
        'Webber',
        'DOCTOR',
        (SELECT id FROM clinical.departments WHERE department_code = 'GEN'),
        '+27830000022',
        'richard.webber@hospital.test',
        'ACTIVE',
        '2005-01-01'),
       ('STF-2026-000023',
        'Thabo',
        'Mahlangu',
        'RECEPTIONIST',
        (SELECT id FROM clinical.departments WHERE department_code = 'ADMN'),
        '+27830000023',
        'thabo.mahlangu@hospital.test',
        'ACTIVE',
        '2022-08-15'),
       ('STF-2026-000024',
        'Karin',
        'Visser',
        'BILLING_CLERK',
        (SELECT id FROM clinical.departments WHERE department_code = 'ADMN'),
        '+27830000024',
        'karin.visser@hospital.test',
        'ACTIVE',
        '2020-11-03'),
       ('STF-2026-000025',
        'Precious',
        'Sithole',
        'ADMIN',
        (SELECT id FROM clinical.departments WHERE department_code = 'ADMN'),
        '+27830000025',
        'precious.sithole@hospital.test',
        'ACTIVE',
        '2017-02-27');